name = "ArithmeticReductionDegradationModels"
uuid = "daa07e9f-121b-45a2-ae18-efc927d8cc78"
version = "0.0.1"
authors = ["R cqls <rdrouilh@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.8"
DataFrames = "1.8.1"
Distributions = "0.25.123"
LinearAlgebra = "1.12.0"
Optim = "2.0.0"
Random = "1.11.0"
Serialization = "1.11.0"
StatsBase = "0.34.10"
julia = "1.11"
